services:
  backend:
    container_name: koodnet-api
    build:
      context: .
      dockerfile: ./docker/Dockerfile.koodnet-api
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_URL: postgresql://user:password@localhost:5432/koodnet
  db:
    image: postgres:latest
    restart: always
    container_name: database
    volumes:
      - .data:/var/lib/postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_DB=koodnet
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
