FROM golang:1.22.5-alpine AS golang

WORKDIR /app
COPY . .

RUN go mod download
RUN go mod verify

RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN swag init -g ./cmd/koodnet-api/main.go -o ./docs
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o /koodnet-api cmd/koodnet-api/main.go

FROM gcr.io/distroless/static:latest

COPY --from=golang /koodnet-api .

EXPOSE 8001

CMD ["/koodnet-api"]
