basePath: /api/v1
definitions:
  api.healthResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  api.metadata:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total:
        description: Total represents the total number of items.
        type: integer
      total_pages:
        type: integer
    type: object
  api.paginatedResponse-models_Network:
    properties:
      data:
        description: Data contains the actual collection of items.
        items:
          $ref: '#/definitions/models.Network'
        type: array
      metadata:
        allOf:
        - $ref: '#/definitions/api.metadata'
        description: Metadata contains additional info like the total count.
    type: object
  models.Network:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Server API documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Koodnet API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.healthResponse'
      summary: ping example
      tags:
      - example
  /networks:
    get:
      description: Get a list of all networks with optional pagination
      parameters:
      - default: 1
        description: page for pagination
        in: query
        name: page
        type: integer
      - default: 10
        description: page_size for pagination
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.paginatedResponse-models_Network'
      summary: Get all networks
      tags:
      - networks
swagger: "2.0"
